
package server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DRRSServerService", targetNamespace = "http://Server/", wsdlLocation = "file:/Users/khoatrinh/Documents/SOFTWARE%20ENGINEER/YEAR%203.1/SOEN423%20-%20Distributed%20Systems/Assignments/3/Client/src/server.wsdl")
public class DRRSServerService
    extends Service
{

    private final static URL DRRSSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException DRRSSERVERSERVICE_EXCEPTION;
    private final static QName DRRSSERVERSERVICE_QNAME = new QName("http://Server/", "DRRSServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/khoatrinh/Documents/SOFTWARE%20ENGINEER/YEAR%203.1/SOEN423%20-%20Distributed%20Systems/Assignments/3/Client/src/server.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DRRSSERVERSERVICE_WSDL_LOCATION = url;
        DRRSSERVERSERVICE_EXCEPTION = e;
    }

    public DRRSServerService() {
        super(__getWsdlLocation(), DRRSSERVERSERVICE_QNAME);
    }

    public DRRSServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DRRSSERVERSERVICE_QNAME, features);
    }

    public DRRSServerService(URL wsdlLocation) {
        super(wsdlLocation, DRRSSERVERSERVICE_QNAME);
    }

    public DRRSServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DRRSSERVERSERVICE_QNAME, features);
    }

    public DRRSServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DRRSServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DRRSServer
     */
    @WebEndpoint(name = "DRRSServerPort")
    public DRRSServer getDRRSServerPort() {
        return super.getPort(new QName("http://Server/", "DRRSServerPort"), DRRSServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DRRSServer
     */
    @WebEndpoint(name = "DRRSServerPort")
    public DRRSServer getDRRSServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Server/", "DRRSServerPort"), DRRSServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DRRSSERVERSERVICE_EXCEPTION!= null) {
            throw DRRSSERVERSERVICE_EXCEPTION;
        }
        return DRRSSERVERSERVICE_WSDL_LOCATION;
    }

}
